### ISSUE TITLE
[1.12] Crash with Artisan Worktables 

### ISSUE THREAD

**Issue by MasterEnderman** [YaLTeR/MouseTweaks#14]
Crash Report: https://paste.dimdev.org/igoyacexig.mccrash

**Comment by YaLTeR** [comment]
Hello, did you report this to Artisan Worktables? I suspect that the issue is on their side.

**Comment by YaLTeR** [comment]
Thanks!

**Comment by NillerMedDild** [comment]
I'm experiencing a very similar bug, but with the Tinkers' Crafting Station. The stacktrace seems to point to MouseTweaks.

https://gist.github.com/NillerMedDild/9ff8722be333407bf44200b10ac41f43

**Comment by YaLTeR** [comment]
That one looks very much like a craft tweaker misconfiguration. Look: Mouse Tweaks "clicks" the slots in the container via reflection, and what this report indicates is that the container threw an exception:

```
Description: handleMouseClick() threw an exception when called from MouseTweaks.

java.lang.reflect.InvocationTargetException
    <some lines of stack trace>
```

and right after the first stack trace it tells you the actual exception and its stack trace:

```
Caused by: java.lang.NumberFormatException: For input string: "orechid"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Byte.parseByte(Unknown Source)
	at java.lang.Byte.parseByte(Unknown Source)
	at crafttweaker.api.data.DataString.asByte(DataString.java:25)
	at crafttweaker.api.data.DataByte.contains(DataByte.java:105)
	at crafttweaker.api.data.DataMap.contains(DataMap.java:229)
	at crafttweaker.mc1120.item.MCItemStack.matchesExact(MCItemStack.java:350)
	at crafttweaker.mc1120.item.MCItemStack.matches(MCItemStack.java:327)
	at crafttweaker.mc1120.recipes.MCRecipeShapeless.func_77569_a(MCRecipeShapeless.java:50)
	at net.minecraft.item.crafting.CraftingManager.func_192413_b(CraftingManager.java:213)
	at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.func_192389_a(ContainerCraftingStation.java:165)
	at slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation.func_75130_a(ContainerCraftingStation.java:157)
	at slimeknights.tconstruct.shared.inventory.InventoryCraftingPersistent.onCraftMatrixChanged(InventoryCraftingPersistent.java:114)
	at slimeknights.tconstruct.shared.inventory.InventoryCraftingPersistent.func_70299_a(InventoryCraftingPersistent.java:90)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at slimeknights.mantle.inventory.ContainerMultiModule.func_184996_a(ContainerMultiModule.java:121)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
... 22 more
```

**Comment by NillerMedDild** [comment]
Cool, thank you. I have reported the issue to the Crafttweaker repo.
